[project]
name = "steamrichpresencewatcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "discord-py[speed]>=2.7.1",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.142.2",
    "orjson>=3.12.0",
    "pydantic-settings>=2.15.0",
    "steamio>=1.2.0",
]

[dependency-groups]
dev = ["asyncpg-stubs>=0.31.3"]

[tool.uv.sources]
steamio = { git = "https://github.com/Aluerie/steam.py", rev = "introduce-ext.dota2" }


[tool.ty.rules]
all = "error"
dynamic-function-decorator-return = "ignore" # TwitchIO's decorators return `Any`
possibly-missing-import = "ignore" # False positives, maybe we'll try it later.
unsound-assignment = "ignore" # `Any` is fine
unsound-return-statement = "ignore" # `Any` is fine
unsound-yield = "ignore" # `Any` is fine


[tool.ruff]
line-length = 125
target-version = "py314"
preview = true
exclude = [".venv"]
src = ["src"]


[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # Recommended to disable by https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "tab-indentation",
    "indentation-with-invalid-multiple",
    "indentation-with-invalid-multiple-comment",
    "over-indented",
    "incorrect-blank-line-before-class",
    "docstring-tab-indentation",
    "triple-single-quotes",
    "bad-quotes-inline-string",
    "bad-quotes-multiline-string",
    "bad-quotes-docstring",
    "avoidable-escaped-quote",
    "unnecessary-escaped-quote",
    "missing-trailing-comma",
    "prohibited-trailing-comma",
    "multi-line-implicit-string-concatenation",
    # Docstring related
    "D",
    "DOC",
    # Complexity memes
    "complex-structure",
    "too-many-arguments",
    "too-many-branches",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-statements-in-try-clause",
    "too-many-return-statements",
    # Todo
    "line-contains-todo",
    "missing-todo-author",
    "missing-todo-link",
    # Other (uncategorized) Rules
    "any-type",
    "assert",
    "commented-out-code",
    "implicit-namespace-package",
    "magic-value-comparison",
    "missing-copyright-notice",
    "non-empty-init-module",
]
unfixable = []
flake8-quotes.inline-quotes = "double"


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
split-on-trailing-comma = true
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"
